--- #YAML:1.0
name:                nagiosgraph
version:             1.1.0
abstract:            Nagios performance data storage and graphing
license:             ~
author:              
    - Alan Brenner <alan.brenner@ithaka.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    RRDs:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
