--- #YAML:1.0
name:                nagiosgraph
version:             1.4.4
abstract:            Nagios performance data storage and graphing
license:             OSI Artistic License
author:              
    - Alan Brenner <alan.brenner@ithaka.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:            0
    CGI:             0
    Data::Dumper:    0
    English:         0
    Exporter:        0
    Fcntl:           0
    File::Basename:  0
    File::Copy:      0
    File::Find:      0
    File::Path:      0
    MIME::Base64:    0
    POSIX:           0
    RRDs:            0
    Time::HiRes:     0
recommends:
    GD:              0
build_requires:
    FindBin:         0
    Test:            0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
