#!/bin/sh

# remove apache configuration changes
rm /etc/apache2/conf.d/nagiosgraph.conf

# remove nagios configuration changes
# FIXME: this assumes that no changes were made since we cached to -ngsave
mv /etc/nagios3/nagios.cfg-ngsave /etc/nagios3/nagios.cfg
mv /etc/nagios3/commands.cfg-ngsave /etc/nagios3/commands.cfg

# restart apache and nagios
/etc/init.d/apache2 restart
/etc/init.d/nagios3 restart
