#!/bin/sh

# set permissions on nagiosgraph files
chmod 755 /var/spool/nagiosgraph/rrd
chown nagios /var/spool/nagiosgraph/rrd
chmod 775 /var/log/nagiosgraph
chown nagios:www-data /var/log/nagiosgraph
chown nagios:adm /var/log/nagiosgraph/nagiosgraph.log
chown www-data:adm /var/log/nagiosgraph/nagiosgraph-cgi.log

# configure apache
cp /etc/nagiosgraph/nagiosgraph-apache.conf /etc/apache2/conf.d/nagiosgraph.conf

# configure nagios
cp -p /etc/nagios3/nagios.cfg /etc/nagios3/nagios.cfg-saved
cat /etc/nagiosgraph/nagiosgraph-nagios.cfg >> /etc/nagios3/nagios.cfg
cp -p /etc/nagios3/commands.cfg /etc/nagios3/commands.cfg-saved
cat /etc/nagiosgraph/nagiosgraph-commands.cfg >> /etc/nagios3/commands.cfg

# restart apache and nagios
/etc/init.d/apache2 restart
/etc/init.d/nagios3 restart
